version: '3.9'

name: 'opinions'

services:
  # REDIS SERVICE
  redis:
    container_name: redis_cache
    image: redis:7.0.5-alpine
    restart: always
    volumes:
      - ./op-devops/docker/.data/redis:/data
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - opinions_network

  # DEVELOPMENT BACKEND SERVER
  op-backend-host:
    container_name: op-backend-server
    restart: always
    command: yarn start:dev
    volumes:
      - ./op-backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - opinions_network
    build:
      context: ./op-backend
      target: development
    depends_on:
      - redis
    env_file:
      - ./op-backend/.env
    environment:
      REDIS_HOST: redis

  # DEVELOPMENT FRONTEND SERVER
  op-frontend-client:
    container_name: op-frontend-server
    restart: always
    command: yarn dev
    networks:
      - opinions_network
    build:
      context: ./op-frontend
      target: development
    env_file:
      - ./op-frontend/.env
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  # NGINX SERVICE
  nginx:
    container_name: nginx_proxy
    image: nginx:1.22-alpine
    restart: unless-stopped
    volumes:
      - ./op-devops/docker/nginx/templates/:/etc/nginx/templates
    ports:
      - 80:80
    networks:
      - opinions_network
    env_file:
      - ./op-backend/.env
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: '.conf'
      API_HOST: op-backend-server
    depends_on:
      - op-backend-host
      - op-frontend-client


networks:
  opinions_network:
